### ISSUE TITLE
Week04 ready for reveiw.

### ISSUE THREAD

**Issue by chstudebaker** [chstudebaker/herobase#3]
What were your key learning points/takeaways?
The unit tests challenged me. Learning to run them without errors was a challenge in itself
What challenged you?
Getting the database configured
What problems did you solve and what resources did you use to solve them?
AI certainly helped with a lot of the SQL statement debugging, as well as troubleshooting various stack overflow errors I received

**Comment by pawaitemadisoncollege** [comment]
Hi @chstudebaker! It's great to see that you've started working a bit with hibernate.

For your week 4 work to meet expectations:

- [ ] You should be able to run all unit tests together (at the same time).  Please take new screenshots showing them all running successfully in a single execution. Note that each test should be completely independent of any other test.
- [ ] Your HeroDaoTest is missing a step to reset the database between each test so that you can run all tests together. 
- [ ] Do not use HQL. This does not follow best practices - the hard-coding of sql like this makes the application more brittle by closely tying the dao to the database. https://github.com/chstudebaker/herobase/blob/1492a51f491b47ff4c1973e74445a8e4918e8d9a/src/main/java/persistance/HeroDao.java#L42 and https://github.com/chstudebaker/herobase/blob/1492a51f491b47ff4c1973e74445a8e4918e8d9a/src/main/java/persistance/HeroDao.java#L55. The beauty of hibernate is that you can avoid having to write sql. The hard-coded sql approach will also make it much more difficult to implement a single dao for use with all of your entities. 

I also noticed you are using the include directive, https://github.com/chstudebaker/herobase/blob/1492a51f491b47ff4c1973e74445a8e4918e8d9a/src/main/webapp/addHero.jsp#L2. It is a best practice to use the jstl tag instead. 

Please respond to this issue when you've made the revisions above. Thanks!

**Comment by chstudebaker** [comment]
@pawaitemadisoncollege Week 04 corrections have been made. Ready for re-review

**Comment by pawaitemadisoncollege** [comment]
@chstudebaker! You have made some good improvements based on previous feedback.

- [ ] This method isn't necessary. Your Hero entity has a list of powers on it already. This is another of the useful  things about using an ORM, you don't have to write extra sql/dao code to get at the associations. https://github.com/chstudebaker/herobase/blob/e176bcfb73e7d35769cf5a3d12cb89eae7cc8c51/src/main/java/persistance/HeroDao.java#L63-L75
- [ ] Tests do not cover 100% of the methods in the dao, for example: https://github.com/chstudebaker/herobase/blob/e176bcfb73e7d35769cf5a3d12cb89eae7cc8c51/src/main/java/persistance/HeroDao.java#L48C23-L48C35 and https://github.com/chstudebaker/herobase/blob/e176bcfb73e7d35769cf5a3d12cb89eae7cc8c51/src/main/java/persistance/HeroDao.java#L26
- [ ] Your cleandb.sql recreates the database but doesn't appear to add any records.  Is what's in GitHub current?  https://github.com/chstudebaker/herobase/blob/e176bcfb73e7d35769cf5a3d12cb89eae7cc8c51/src/test/resources/cleandb.sql#L1-L19
- [ ] The database class is used only for unit testing, so it doesn't below in the "production" code. Move this down into a util package under test. 
- [ ] Check versions in the pom.xml. Some are hard-coding and might be an older version. Example: https://github.com/chstudebaker/herobase/blob/e176bcfb73e7d35769cf5a3d12cb89eae7cc8c51/pom.xml#L109
- [ ] Screenshots are missing code coverage info. 

Let me know when that's ready and I'll take another look.

**Comment by chstudebaker** [comment]
@pawaitemadisoncollege 
Hello again.

I fixed these things:

Removed unessasary methods from the Dao's

Added Unit tests I was missing

Acheived full coverage for HeroDaoTests

Ran all tests at the same time. All passed

Updated the clean DB.sql with my dump file.

However, about that hard coded value. Ive tried updating it multiple times by putting it in a properties variable, and it keeps being rejected. Apparently it doesn't like any higher version. I did update the other hibernate dependencies, so its just the one that keeps giving me trouble.

That should be all, but let me know if i need to make further alterations.

**Comment by pawaitemadisoncollege** [comment]
Hi @chstudebaker! You made some good progress here!

Here is what I noticed:

- [ ] You should not need the hibernate annotation dependency in the pom, just core and c3po, for basic hibernate integration. If you are finding that you "need" it, it's possible you aren't using the recommended annotations - compare to the demos.
- [ ] You shouldn't need to explicitly delete the associated powers here - if the db and annotations are set up correctly, this will happen automatically. https://github.com/chstudebaker/herobase/blob/e1cafcb6a7a78a34860f5347d04ea50092bae3f1/src/main/java/persistance/HeroDao.java#L101-L105. Similar issue with the insert - the specificity you have in these methods will make "abstracting/genericizing" these with the generic dao difficult. The generic dao is required (you should add it after week 4 and 5 exercise work is complete to standards/best practices).  Example, you can use  a dao to insert power and a dao to insert a hero with those powers. Or your can create the hero, and then use an addPower method to insert powers - refer to the demos for examples.
- [ ] The java dao test files are currently empty - seem to have been moved to .txt files? Why is this?

**Comment by chstudebaker** [comment]
@pawaitemadisoncollege 
Alright, Ive updated the methods to use cascade.TYPE=ALL, and now they can implicitly delete or edit stuff. I also got rid of the hibernate annotations dependency, guess I didn't need it after all

As for the tests. I often have to run the program broken so that I can debug features. However because I know its broken, I know the tests will error out and prevent me from building the program at all. I put them in the txt files temporarily while I correct mistakes, then take them out again when Im ready to test the webapp. If you know a better way to accomplish this, let me know. 

added corrected testing screenshots to the repo, so this should be all changes made.

**Comment by pawaitemadisoncollege** [comment]
Responding only to the tests comment - if you need to deploy locally (in an "emergency") you can turn off the tests in the maven view so that you don't have to move things around like this. I think the button/icon to toggle the tests looks like a NO symbol - circle with a line through it. That'll allow you to bypass the tests (just remember to turn them back on reg!).

I'll circle back and review the other items over the next few days. Remember to check off what is complete in the issues :)

**Comment by pawaitemadisoncollege** [comment]
Good work @chstudebaker! 

Next steps are to:
- [ ] Remove those txt. files and put back the .java tests. Toggle the tests in the maven view if you have a need to do an emergency deployment for some reason as mentioned above.  
- [ ] Implement .equals on your entities for more thorough and easier entity comparison than comparing very instance var like this: https://github.com/chstudebaker/herobase/blob/dedfa06241111f41cd115fe422f6c32534b3b769/src/test/java/persistance/heroDoaTest.txt#L73-L76. There was a video about this earlier in the course if you need a reference.
- [ ] Implement the generic dao in your project so that you can use a single dao! Note that you will still have unit tests each for each entity(dao) to make sure that annotations and database relationships are set up correctly. Remove existing entity-specific-daos once the generic dao is fully implemented and tested.
