### ISSUE TITLE
Week07 ready for review

### ISSUE THREAD

**Issue by chstudebaker** [chstudebaker/herobase#4]
@pawaitemadisoncollege Week07 ready for review

What were your key learning points/takeaways?
Http sites do not work with cognito. The url's matter
What challenged you?
Getting it set up for Http and not https
What problems did you solve and what resources did you use to solve them?
see above. I used help channel and AI to troubleshoot this.

**Comment by pawaitemadisoncollege** [comment]
Hi @chstudebaker, nice job setting up cognito in your project.  Be sure to check out the flow I posted in Slack week07 channel to understand how you can now use cognito and the auth flow to add users to your database. 

Note that you can use http with cognito in a local environment only. 

- [ ] It sounds like you have this deployed on AWS? If so, please add your deployed app url to the list of indie projects in the student repository. Thanks! 
- [ ] Best practices: in this method you have the error page hard-coded several times. Use a constant for this instead of hard-coding. https://github.com/chstudebaker/herobase/blob/1492a51f491b47ff4c1973e74445a8e4918e8d9a/src/main/java/controller/Auth.java#L74-L87

**Comment by chstudebaker** [comment]
No. I cant deploy to aws as i dont have mysql sql server set up yet. Once i
get back to school, i will get this deployed.

**Comment by chstudebaker** [comment]
@pawaitemadisoncollege No. I cant deploy to aws as i dont have mysql sql server set up yet. Once i
get back to school, i will get this deployed.

**Comment by chstudebaker** [comment]
@pawaitemadisoncollege other than that. I updated the Error page link to be a constant called ERROR_PAGE
