### ISSUE TITLE
Checkpoint 3

### ISSUE THREAD

**Issue by chstudebaker** [chstudebaker/herobase#8]
@pawaitemadisoncollege 

Deployed to AWS
Integrated cognito functionality with AWS
HeroList, SearchHero, and Index pages all display data from database
Link to deployed app posted in GIT

**Comment by pawaitemadisoncollege** [comment]
Hi @chstudebaker! I was able to sign up, log in, and view data using the link for your indie project listed in the student repo.  that meets the core of CP3. Well done! The site looks really nice with the images in the Hero list!

As I was testing out CP 3, I noticed a few things related to best practices that could be improved:

- [ ] Rather than showing the delete icon to all users, allowing them to click it and then show they aren't signed in/authorized. It would be better to not show the delete icon/button unless a user is logged in.
- [ ] Add Powers to Hero page, and similar add/edits - rather than requiring that the user know the hero id, provide a dropdown of hero names to use when adding a power. 
- [ ] I noticed the edit and delete buttons do not show up consistently on the hero detail page - they seem to appear on either a click or hover type event. It would be better to consistently show these so the user knows the options are available.
